import type {Metadata} from "next";
import { Lato} from "next/font/google";
import "./globals.css";

const lato = Lato({
    variable: '--font-lato-sans',
    weight:['100', '300', '400', '700', '900'],
    subsets:['latin']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                       header
                                   }: Readonly<{
    children: React.ReactNode;
    header: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${lato.className} antialiased`}
        >
        {header}
        {children}
        </body>
        </html>
    );
}
